# Create runtime dir for wjs
# It holds the unix sockets used by the instances' gunicorn units and apache to
# communicate, one per instance (see systemd/gunicorn.service.j2)
#Type Path     Mode User Group     Age Argument
d     /run/wjs 0770 wjs  www-data  -   -
