# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "(.idea|node_modules|.tox|^wjs/jcom_profile/tests/aux/.*\\.html$)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: fix-encoding-pragma
        args:
          - --remove
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-broken-line
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-eradicate
          - pep8-naming
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - toml
        # temporary exclusion of the project root to give us time to add the missing documentation
        exclude: |
          (?x)(
              ^wjs/|
              ^wjs/jcom_profile/migrations/|
              ^^wjs/jcom_profile/tests/
          )
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-django
        exclude: '.*/tests/.*\.html$'
  - repo: https://github.com/pre-commit/mirrors-prettier
    # the actually used version is the one below in additional dependencies, pre-commit mirror does not support
    # prettier versions well, the manual pin below is a good way to pin the version
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        files: '\.(jsx?|tsx?|css|scss)$'
        additional_dependencies:
          - prettier@2.8.0
