[build-system]
requires = ['setuptools>=78.1.1', 'wheel']
build-backend = 'setuptools.build_meta:__legacy__'

[tool.black]
line-length = 119
target-version = ['py39']
include = '/((wjs)/.*\.pyi?|.*\.py)$'

[tool.isort]
profile = "black"

[tool.pydocstyle]
ignore = ["D101","D104", "D105","D106","D212","D203","D213"]

[tool.djlint]
profile="django"
ignore="H006"

[tool.ruff]
target-version = "py311"
line-length = 119

[tool.ruff.lint]
preview = true
select = ["ALL"]
# A003 is triggered only sometimes!
ignore = [
  "COM819",
  "EM101",
  "D212","D203",
  "CPY001",
  "G004",  # logging statement uses f-string
  "DOC201",  # "return" is not documented in docstring (too invasive)
  "ANN002",  # missing return type annotation for *args
  "ANN003",  # missing return type annotation for **kwargs
  "ANN201",  # missing return type annotation (too invasive, expecially for "-> None" cases)
  "ANN202",  # missing return type annotation
  "ANN204",  # missing return type annotation for special method
  "TRY003",  # long message outside the exception class
  "EM102",  # Exception must not use an f-string literal, assign to variable first
  "TID252",  # Relative imports
]

fixable = ["ALL"]
unfixable = []
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = [
  "S101",
  "PLR0913",  # Too many arguments in function definition
  "PLR0917",  # Too many positional arguments
]
