[build-system]
requires = ['setuptools>=40.8.0', 'wheel']
build-backend = 'setuptools.build_meta:__legacy__'

[tool.black]
line-length = 119
target-version = ['py39']
include = '/((wjs)/.*\.pyi?|.*\.py)$'

[tool.isort]
profile = "black"

[tool.pydocstyle]
ignore = ["D101","D104", "D105","D106","D212","D203","D213"]

[tool.djlint]
profile="django"
ignore="H006"

[tool.ruff]
target-version = "py311"
line-length = 119

[tool.ruff.lint]
preview = true
select = ["ALL"]
# A003 is triggered only sometimes!
ignore = [
  "COM819",
  "EM101",
  "D212","D203",
  "CPY001",
  "G400",  # logging statement uses f-string
  "DOC201",  # "return" is not documented in docstring (too invasive)
  ]

fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = ["S101"]
