[metadata]
name = wjs.jcom_profile
version = 1.0.67
description = Enrich Janeway user profile
url = https://medialab.sissa.it/
author = Matteo
author_email = gamboz@medialab.sissa.it
license = AGPL
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Intended Audience :: Developers
    License :: OSI Approved :: AGPL License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.9
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content

[options]
include_package_data = true
packages = find_namespace:
python_requires = >=3.9
install_requires =
    Django ~= 4.2
    django-easy-select2
    pandas ~= 2.0
    odfpy
    django-sortedm2m ~= 3.1
    premailer
    pycountry
    django-rosetta
    mariadb
    django-model-utils ~= 4.3.1
    django-fsm ~= 2.8.1
    requests-toolbelt ~= 1.0.0
    django-filter ~= 23.5
    django-q2 ~= 1.6.0
    croniter ~= 2.0.0
    redis ~= 6.2.0
    blessed ~= 1.20
    pip-audit
    django-redis ~= 5.4.0
    channels
    channels-redis
    wjs-themes >= 0.0.5
    wjs-submission
    daphne
    channels
    channels-redis
    websockets
    daphne
    autobahn~=25.10

[options.extras_require]
test =
    pytest == 8.3.3  # temporary workaround for wjs-profile-project#204
    pytest-django
    pytest-factoryboy
    pytest-mock
    pytest-freezegun
    pytest-xdist
    pytest-reverse
    wjs_mgmt_cmds ~= 0.4.2rc1

[options.package_data]
* =
    *.html
    *.css
    *.woff
    *.woff2
    *.js
    *.scss
    *.po
    *.mo
    *-redirects.inc
    *.png

[flake8]
exclude = ./.*,**/migrations/*,**/*settings.py
max-line-length = 119
# flake8-quotes
inline-quotes = double
# flake8-coding
no-accept-encodings = True
# flake8-tidy-imports
banned-modules = __future__ = this project supports python3 only

[pycodestyle]
max-line-length = 119

[pydocstyle]
ignore = D102, D200, D203, D212, D213

[options.entry_points]
console_scripts =
    count_recipients = wjs.jcom_profile.management.commands._count_recipients:main
