#!/usr/bin/env bash

# NB: need -e because of how we run pytest in ci/cd test job
pip install --extra-index-url=https://gitlab.sissamedialab.it/api/v4/projects/60/packages/pypi/simple -e ${CI_PROJECT_DIR}/[test]
cd /janeway/src/plugins && for p in `ls -1d ${CI_PROJECT_DIR}/wjs/plugins/wjs*`; do ln -s $p; done
cd /janeway/src
cp ${CI_PROJECT_DIR}/cicd_* core
# This is needed to sync extra janeway fields registered as translatable in wjs
python3 manage.py makemigrations --no-input > /dev/null 2>&1
python3 manage.py migrate --no-input --run-syncdb
python3 manage.py install_plugins
python3 manage.py install_themes
