[metadata]
name = wjs.jcom_profile
version = 2.0.16
description = Enrich Janeway user profile
url = https://medialab.sissa.it/
author = Matteo
author_email = gamboz@medialab.sissa.it
license = AGPL-3.0-or-later
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Intended Audience :: Developers
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.11
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content

[options]
include_package_data = true
packages = find_namespace:
python_requires = >=3.9
install_requires =
    Django ~= 4.2
    django-easy-select2
    pandas ~= 2.0
    odfpy
    django-sortedm2m ~= 4.0
    premailer
    pycountry
    django-rosetta
    mariadb
    django-model-utils ~= 5.0
    django-fsm-2 ~= 4.2.0
    requests-toolbelt ~= 1.0.0
    django-filter ~= 25.1
    django-q2 ~= 1.9.0
    croniter ~= 2.0.0
    redis ~= 6.2.0
    blessed ~= 1.20
    pip-audit
    django-redis ~= 5.4.0
    channels
    channels-redis
    wjs-themes >= 2.0.13
    wjs-submission >= 2.0.7
    channels
    channels-redis
    websockets
    pypandoc
    uvicorn
    uvicorn-worker
    gunicorn
    # Constraints:
    # the following pins are for second-level dependencies that
    # had some security issue and that we needed to upgrade
    autobahn~=25.10
    cbor2~=5.9.0
    filelock ~= 3.20.3
    djangorestframework ~= 3.17.1
    pygments ~= 2.20.0
    ujson ~= 5.13.0

[options.extras_require]
test =
    pytest == 8.3.3  # temporary workaround for wjs-profile-project#204
    pytest-django
    pytest-factoryboy
    pytest-mock
    pytest-freezegun
    pytest-xdist
    pytest-reverse
    wjs_mgmt_cmds ~= 0.5.0

[options.package_data]
* =
    *.html
    *.css
    *.woff
    *.woff2
    *.js
    *.scss
    *.po
    *.mo
    *-redirects.inc
    *.png

[flake8]
exclude = ./.*,**/migrations/*,**/*settings.py
max-line-length = 119
# flake8-quotes
inline-quotes = double
# flake8-coding
no-accept-encodings = True
# flake8-tidy-imports
banned-modules = __future__ = this project supports python3 only
per-file-ignores= wjs/jcom_profile/profile/__init__.py:A005

[pycodestyle]
max-line-length = 119

[pydocstyle]
ignore = D102, D200, D203, D212, D213

[options.entry_points]
console_scripts =
    count_recipients = wjs.jcom_profile.management.commands._count_recipients:main
