#!/usr/bin/env bash

# Die on errors
set -e

# echo in blue color
export TERM=${TERM:-xterm-256color}
info () {
    >&2 echo $(tput setaf 4)"$@"$(tput sgr0)
}
export -f info

export PGPASSWORD=${POSTGRES_PASSWORD}

info "Installing pandoc..."
apt-get update -qq && apt-get install -y pandoc

info "Installing wjs..."
# NB: need -e because of how we run pytest in ci/cd test job
pip install --extra-index-url=https://gitlab.sissamedialab.it/api/v4/projects/60/packages/pypi/simple -e ${CI_PROJECT_DIR}/[test]

info "Linking plugins..."
cd /janeway/src/plugins && rm -f wjs*  # cleanup plugins directory
cd /janeway/src/plugins && for p in `ls -1d ${CI_PROJECT_DIR}/wjs/plugins/wjs*`; do ln -s $p; done
cd /janeway/src/plugins && for p in `ls -1d /usr/local/lib/python3.11/site-packages/wjs/plugins/wjs*`; do ln -s $p; done
cd /janeway/src

info "Cloning third-party plugins..."
# Hydra (linking of articles across and within journals) is not distributed as a
# python package, so we clone it at a pinned ref. Any directory in src/plugins is
# automatically added to INSTALLED_APPS by Janeway (see core.plugin_installed_apps),
# and the `install_plugins` call below registers it in the DB.
# Keep in sync with setup-docs/ansible/wjs-test__create-instance__wjs.yml and
# setup-docs/ansible/scripts/deploy.sh
HYDRA_REPO=${HYDRA_REPO:-https://gitlab.sissamedialab.it/wjs/hydra.git}
HYDRA_REF=${HYDRA_REF:-wjs-production}
rm -rf /janeway/src/plugins/hydra
git clone --quiet "${HYDRA_REPO}" /janeway/src/plugins/hydra
git -C /janeway/src/plugins/hydra checkout --quiet "${HYDRA_REF}"
cd /janeway/src

info "Copying settings modules..."
cp ${CI_PROJECT_DIR}/cicd_* core

# Load an almost-ready DB to speed-up setup
#
# To regenerate:
# docker-compose -f docker-compose-test-local.yml run janeway /bin/bash
# then, from inside the container, run some of the steps of this script
# - do _not_ pip install...
# - do _not_ link plugins
# - edit settings module:
#   - cd /janeway/src
#   - cp ${CI_PROJECT_DIR}/cicd_* core
#   - sed -i 's/from/# from/' core/cicd_settings.py
# - skip db dump/restore part
# - do _not_ makemigrations
# - migrate
# - pg_dump -h db -U janeway -f /host-tmp/janeway-db-dump.sql janeway
# You should now have a new dump in the host's /tmp.

info "Loading prepared DB..."
db_dump=janeway-db-dump.sql
dropdb -h db -U janeway --if-exists janeway
createdb -h db -U janeway janeway
bunzip2 -c ${CI_PROJECT_DIR}/${db_dump}.bz2 | python3 manage.py dbshell > /dev/null

info "Syncing languages translations..."
# This is needed to sync extra janeway fields registered as translatable in wjs
python3 manage.py makemigrations --no-input > /dev/null
python3 manage.py migrate --no-input --run-syncdb

info "Installing plugins and themes..."
python3 manage.py install_plugins
python3 manage.py install_themes

# info "Patch settings..." (not needed because of wjs_review.tests.conftest.review_settings)
# # ensure all janeway settings are present (docker image migh lag behind...)
# python3 manage.py load_default_settings
# # apply our defaults settings and our default values to Janeway's settings
# python3 manage.py apply_wjs_settings
# # python3 manage.py setup_review_settings --force  # not needed ATM
# python3 manage.py create_custom_settings --force  # not needed ATM

info "Environment ready for tests."
