# Generated by Django 3.2.19 on 2023-09-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_latest_news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_count",
            field=models.PositiveSmallIntegerField(default=10, help_text="Number of items shown in the second box"),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_tag",
            field=models.CharField(
                default="call", help_text="Tag used to filter news visible in second box", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_title",
            field=models.CharField(default="Call for papers", help_text="Title of the second box", max_length=500),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_title_cy",
            field=models.CharField(
                default="Call for papers", help_text="Title of the second box", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_title_de",
            field=models.CharField(
                default="Call for papers", help_text="Title of the second box", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_title_en",
            field=models.CharField(
                default="Call for papers", help_text="Title of the second box", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_title_es",
            field=models.CharField(
                default="Call for papers", help_text="Title of the second box", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_title_fr",
            field=models.CharField(
                default="Call for papers", help_text="Title of the second box", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_title_nl",
            field=models.CharField(
                default="Call for papers", help_text="Title of the second box", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="secondbox_title_pt",
            field=models.CharField(
                default="Call for papers", help_text="Title of the second box", max_length=500, null=True
            ),
        ),
    ]
