# Generated by Django 4.2.30 on 2026-06-11 11:29

import core.model_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0068_issue_allowed_sections_issue_cached_display_title_pt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_column_items",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Number of items in main column"),
                ),
                (
                    "title_1",
                    models.CharField(default="", verbose_name="Title block 1", max_length=500),
                ),
                (
                    "content_1",
                    core.model_utils.JanewayBleachField(default="", verbose_name="Content block 1"),
                ),
                (
                    "title_2",
                    models.CharField(default="", verbose_name="Title block 2", max_length=500),
                ),
                (
                    "content_2",
                    core.model_utils.JanewayBleachField(default="", verbose_name="Content block 2"),
                ),
                (
                    "title_3",
                    models.CharField(default="", verbose_name="Title block 3", max_length=500),
                ),
                (
                    "content_3",
                    core.model_utils.JanewayBleachField(default="", verbose_name="Content block 3"),
                ),
                (
                    "title_4",
                    models.CharField(default="", verbose_name="Title block 4", max_length=500),
                ),
                (
                    "content_4",
                    core.model_utils.JanewayBleachField(default="", verbose_name="Content block 4"),
                ),
                (
                    "title_login_box_auth",
                    models.CharField(
                        default="",
                        verbose_name="Title Login Box - Logged in users",
                        max_length=500,
                    ),
                ),
                (
                    "content_login_box_auth",
                    core.model_utils.JanewayBleachField(
                        default="",
                        verbose_name="Content Login Box - Logged in users",
                        max_length=500,
                    ),
                ),
                (
                    "title_login_box_unauth",
                    models.CharField(
                        default="",
                        verbose_name="Title Login Box - Non logged in users",
                        max_length=500,
                    ),
                ),
                (
                    "content_login_box_unauth",
                    core.model_utils.JanewayBleachField(
                        default="",
                        verbose_name="Content Login Box - Non logged in users",
                        max_length=500,
                    ),
                ),
                (
                    "title_personal_area_auth",
                    models.CharField(
                        default="",
                        verbose_name="Title Personal area - Logged in users",
                        max_length=500,
                    ),
                ),
                (
                    "content_personal_area_auth",
                    core.model_utils.JanewayBleachField(
                        default="",
                        verbose_name="Content Personal area - Logged in users",
                        max_length=500,
                    ),
                ),
                (
                    "title_personal_area_unauth",
                    models.CharField(
                        default="",
                        verbose_name="Title Personal area - Non logged in users",
                        max_length=500,
                    ),
                ),
                (
                    "content_personal_area_unauth",
                    core.model_utils.JanewayBleachField(
                        default="",
                        verbose_name="Content Personal area - Non logged in users",
                        max_length=500,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wjs_home_blocks_plugin_config",
                        to="journal.journal",
                    ),
                ),
                (
                    "show_login_in_personal_area",
                    models.BooleanField(default=False, verbose_name="Show login box in personal area block"),
                ),
            ],
        ),
    ]
