import:
  hosts:
    wjs-import:
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

test:
  hosts:
    wjs-test:
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3.11
