# Maintenance mode setup.
# Just provide the necessary files. This playbook does not enable the maintenance mode.
# For that, please connect to the machine and run:
# a2ensite wjs-maintenance && systemctl reload apache2.service
#
# Once done, disable maintenance mode:
# a2dissite wjs-maintenance && systemctl reload apache2.service

---
- name: Provide maintenance mode setup
  hosts: test
  remote_user: root
  become: yes
  vars:
    # Define variables that can be passed through the CL, e.g.:
    # ansible-playbook setup-docs/ansible/to-gunicorn.yml \
    #   -e "instance_name=dev instance_venv_name=janeway-dev"
    # Note: don't use the save name for the CL variable and for the yml variable
    instance_name: "{{ instance | default('test', true) }}"

  tasks:

    - name: Render and copy Apache virtualhost configuration
      # Note that the template file in "src" is called "wjs-test..."
      # because it's a template for the "wjs-test.ud" machine.
      # Don't confuse with the "test" instance 🙂
      template:
        src: apache/wjs-test-maintenance.conf.j2
        dest: /etc/apache2/sites-available/wjs-{{ instance_name }}-maintenance.conf
        owner: root
        group: root
        mode: '0644'

    - name: Create web directories for journals
      file:
        path: /var/www/maint-pages
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create maintenance pages
      # Note that the file names must agree with DocumentRoot and ErrorDocument
      # defined in wjs-test-maintenance.conf.j2
      template:
        src: apache/maintenance-page.html.j2
        dest: /var/www/maint-pages/{{ instance_name }}-{{ journal | lower }}.maintenance.html
        owner: www-data
        group: www-data
        mode: '0644'
      loop:
        - { journal: 'JCOM', motto: 'Journal of Science Communication' }
        - { journal: 'JCOMAL', motto: 'Journal of Science Communication - América Latina' }
        - { journal: 'JCAP', motto: 'Journal of Cosmology and Astroparticle Physics' }
        - { journal: 'JQuant', motto: 'Journal of Quantum Science' }
        - { journal: 'JHEP', motto: 'Journal of High Energy Physics' }
        - { journal: 'JSTAT', motto: 'Journal of Statistical Mechanics' }
        - { journal: 'JINST', motto: 'Journal of Instrumentation' }
      vars:
        journal: "{{ item.journal }}"
        motto: "{{ item.motto }}"
