# Generated by Django 3.2.19 on 2023-06-18 12:08

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submission", "0071_merge_0070_auto_20230120_1546_0070_auto_20230208_1233"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleWorkflow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("TBA", "To be assigned"),
                            ("ASS", "Assigned"),
                            ("BREF", "Being refereed"),
                            ("WAIT", "Waiting for editors decision"),
                            ("EDREF", "Editor as referee"),
                            ("TBR_MAJOR", "To be revised (major revision)"),
                            ("TBR_MINOR", "To be revised (minor revision)"),
                            ("NOT_SUIT", "Not suitable"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("REJECTED", "Rejected"),
                            ("WAITAPP", "Wait app"),
                            ("WAITAPP_NEW", "Wait app new ed app"),
                            ("ACCEPTED", "Accepted"),
                            ("COPY_WAIT", "Waiting for copyright"),
                            ("COPY_REFUSED", "Copyright refused"),
                        ],
                        default="TBA",
                        max_length=50,
                        verbose_name="State",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="submission.article", verbose_name="Article"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
