# Generated by Django 4.2.16 on 2025-04-07 10:32

import core.model_utils
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import plugins.wjs_review.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journal", "0066_issue_type_bleach_20240507_1359"),
        ("jcom_profile", "0036_add_usernotes"),
        ("core", "0099_alter_accountrole_options"),
        ("submission", "0084_remove_article_jats_article_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("review", "0023_auto_20240312_0922"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("EditorToBeSelected", "Editor to be selected"),
                            ("EditorSelected", "Editor selected"),
                            ("Submitted", "Submitted"),
                            ("ToBeRevised", "To be revised"),
                            ("Withdrawn", "Withdrawn"),
                            ("Rejected", "Rejected"),
                            ("IncompleteSubmission", "Incomplete submission"),
                            ("NotSuitable", "Not suitable"),
                            ("PaperHasEditorReport", "Paper has editor report"),
                            ("Accepted", "Accepted"),
                            ("TypesetterSelected", "Typesetter selected"),
                            ("PaperMightHaveIssues", "Paper might have issues"),
                            ("Proofreading", "Proofreading"),
                            ("ReadyForTypesetter", "Ready for typesetter"),
                            ("Published", "Published"),
                            ("ReadyForPublication", "Ready for publication"),
                            ("SendToEditorForCheck", "Send to editor for check"),
                            ("PublicationInProgress", "Publication in progress"),
                            ("UnderAppeal", "Under appeal"),
                        ],
                        default="IncompleteSubmission",
                        max_length=50,
                        verbose_name="State",
                    ),
                ),
                (
                    "production_flag_no_queries",
                    models.BooleanField(
                        default=False,
                        verbose_name="The latest typesetted files contain no queries for the author",
                    ),
                ),
                (
                    "production_flag_galleys_ok",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Galleys not tested"),
                            (2, "Galleys generation failed"),
                            (3, "Galleys generation succeeded"),
                        ],
                        default=1,
                        verbose_name="The status of the latest galleys",
                    ),
                ),
                (
                    "production_flag_no_checks_needed",
                    models.BooleanField(
                        default=False,
                        verbose_name="No special check is required on the latest typesetted files",
                    ),
                ),
                (
                    "latest_state_change",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("latex_desc", models.TextField(blank=True, null=True)),
                (
                    "social_media_short_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Short description for social media",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "eo_in_charge",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "EO"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="EO in charge",
                    ),
                ),
                (
                    "publication_galleys_source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.file",
                        verbose_name="Source file of the published galleys, prepared by the system from the last TA source files",
                    ),
                ),
                (
                    "supplementary_files_at_acceptance",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="+",
                        to="core.supplementaryfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article workflow",
                "verbose_name_plural": "Article workflows",
            },
        ),
        migrations.CreateModel(
            name="EditorDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            (None, "Select one decision"),
                            ("accept", "Accept"),
                            ("reject", "Reject"),
                            ("minor_revisions", "Minor revision"),
                            ("major_revisions", "Major revision"),
                            ("tech_revisions", "Change Metadata"),
                            ("not_suitable", "Not suitable"),
                            ("requires_resubmission", "Requires resubmission"),
                            ("open_appeal", "Open appeal"),
                        ],
                        max_length=255,
                    ),
                ),
                ("decision_editor_report", models.TextField(blank=True, null=True)),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editor_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Editor",
                    ),
                ),
                (
                    "review_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="review.reviewround",
                        verbose_name="Review round",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="wjs_review.articleworkflow",
                        verbose_name="Article workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor decision",
                "verbose_name_plural": "Editor decisions",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A short description of the message or the subject of the email.",
                        max_length=111,
                        verbose_name="subject",
                    ),
                ),
                (
                    "body",
                    plugins.wjs_review.models.WjsBleachCharField(
                        blank=True,
                        default="",
                        help_text="The content of the message.",
                        max_length=1111,
                        verbose_name="body",
                    ),
                ),
                (
                    "message_type",
                    models.TextField(
                        choices=[
                            ("System log message", "A system message"),
                            (
                                "User hijacked action log message",
                                "A hijacking notification message",
                            ),
                            ("User note", "Notes to self"),
                            ("User message", "User direct message"),
                        ],
                        default="System log message",
                        help_text="Define the message source / scope",
                        verbose_name="Type",
                    ),
                ),
                (
                    "verbosity",
                    models.TextField(
                        choices=[
                            ("Full", "Full message content is sent by email"),
                            ("Timeline", "Timeline only, no email sent"),
                            ("Email", "Email only, not recorded in timeline"),
                        ],
                        default="Full",
                        help_text="Define the message verbosity: ie: the amount of content sent my email / set in the timeline",
                        verbose_name="Verbosity",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "read_by_eo",
                    models.BooleanField(
                        default=False,
                        help_text="True when a member of the EO marks as read a message exchanged by other two actors",
                        verbose_name="Read by EO",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The author of the message (for system message, use wjs-support account)",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="authored_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="from",
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="core.file",
                        verbose_name="Attachments",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "hijacking_actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The real author of the message (if actor has been hijacked)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="authored_messages_as_hijacker",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="hijacker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProphyAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_id", models.IntegerField(unique=True)),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Institution",
                    ),
                ),
                ("articles_count", models.IntegerField(blank=True, null=True)),
                (
                    "authors_groups",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("citations_count", models.IntegerField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(max_length=254, null=True, unique=True, verbose_name="Email"),
                ),
                ("h_index", models.IntegerField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(max_length=900, null=True, verbose_name="Full name"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=300, null=True, verbose_name="First name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Middle name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=300, null=True, verbose_name="Last name"),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Name suffix eg. jr",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "orcid",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="ORCiD"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Prophy author url",
                    ),
                ),
                (
                    "correspondence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jcom_profile.correspondence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WjsSection",
            fields=[
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="submission.section",
                    ),
                ),
                (
                    "doi_sectioncode",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "pubid_and_tex_sectioncode",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "description",
                    core.model_utils.JanewayBleachField(blank=True, default=""),
                ),
            ],
            options={
                "verbose_name": "WJS Section",
            },
            bases=("submission.section",),
        ),
        migrations.CreateModel(
            name="WorkflowReviewAssignment",
            fields=[
                (
                    "reviewassignment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.reviewassignment",
                    ),
                ),
                (
                    "report_form_answers",
                    models.JSONField(default=dict, verbose_name="Report form answers"),
                ),
                (
                    "editor_invite_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editor_invite_messages",
                        to="wjs_review.message",
                        verbose_name="Editor invite message",
                    ),
                ),
            ],
            bases=("review.reviewassignment",),
        ),
        migrations.CreateModel(
            name="WjsEditorAssignment",
            fields=[
                (
                    "editorassignment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.editorassignment",
                    ),
                ),
                (
                    "review_rounds",
                    models.ManyToManyField(
                        blank=True,
                        to="review.reviewround",
                        verbose_name="Managed review rounds",
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor assignment",
                "verbose_name_plural": "Editor assignments",
                "get_latest_by": "assigned",
            },
            bases=("review.editorassignment",),
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("REEA1", "Reviewer should evaluate assignment"),
                            ("REEA2", "Reviewer should evaluate assignment"),
                            ("REEA3", "Reviewer should evaluate assignment"),
                            ("REWR1", "Reviewer should write review"),
                            ("REWR2", "Reviewer should write review"),
                            ("EDSR1", "Editor should select reviewer"),
                            ("EDSR2", "Editor should select reviewer"),
                            ("EDSR3", "Editor should select reviewer"),
                            ("EDMD1", "Editor should make decision"),
                            ("EDMD2", "Editor should make decision"),
                            ("EDMD3", "Editor should make decision"),
                            ("AUMJR1", "Author should submit major revision"),
                            ("AUMJR2", "Author should submit major revision"),
                            ("AUMIR1", "Author should submit minor revision"),
                            ("AUMIR2", "Author should submit minor revision"),
                            ("AUTCR1", "Author should submit technical revision"),
                            ("AUTCR2", "Author should submit technical revision"),
                            ("DIRASED1", "Director should assign editor"),
                            ("DIRASED2", "Director should assign editor"),
                        ],
                        max_length=10,
                        verbose_name="Reminder code",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
                ),
                (
                    "date_due",
                    models.DateField(
                        help_text="The date when the reminder should be sent",
                        verbose_name="Date due",
                    ),
                ),
                (
                    "date_sent",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date when the reminder was sent",
                        null=True,
                        verbose_name="Date sent",
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(default=False, verbose_name="Disabled"),
                ),
                (
                    "clemency_days",
                    models.IntegerField(default=0, verbose_name="Clemency dats"),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "hide_actor_name",
                    models.BooleanField(
                        default=True,
                        help_text="Hide the name of the actor in the message body / subject / From-header",
                        verbose_name="Hide actor name",
                    ),
                ),
                ("message_subject", models.TextField(verbose_name="Message subject")),
                ("message_body", models.TextField(verbose_name="Message body")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders_that_i_send",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders_that_i_receive",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
            },
        ),
        migrations.CreateModel(
            name="ProphyCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(null=True, verbose_name="Prophy score")),
                ("prophy_manuscript_id", models.IntegerField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.article",
                    ),
                ),
                (
                    "prophy_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wjs_review.prophyaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PastEditorAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_assigned", models.DateTimeField(verbose_name="Date assigned")),
                (
                    "date_unassigned",
                    models.DateTimeField(verbose_name="Date unassigned"),
                ),
                (
                    "decline_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select a decline reason"),
                            ("JCOM_BUSY", "Already too busy with JCOM editorial work"),
                            ("BUSY", "Too busy in general"),
                            ("OUTSIDE_EXPERTISE", "Paper outside my area of expertise"),
                            ("NO_REVIEWER", "Unable to find an appropriate reviewer"),
                            ("OTHER", "Other"),
                        ],
                        null=True,
                        verbose_name="Decline reason",
                    ),
                ),
                (
                    "decline_text",
                    models.TextField(blank=True, null=True, verbose_name="Decline optional text"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_editor_assignments",
                        to="submission.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Editor",
                    ),
                ),
                (
                    "review_rounds",
                    models.ManyToManyField(
                        blank=True,
                        to="review.reviewround",
                        verbose_name="Managed review rounds",
                    ),
                ),
            ],
            options={
                "verbose_name": "Past editor assignment",
                "verbose_name_plural": "Past editor assignments",
            },
        ),
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            (
                                "Forward",
                                "The child message is a forward of the parent message.",
                            ),
                            (
                                "Reply",
                                "The child message is a reply to the parent message.",
                            ),
                        ],
                        max_length=101,
                    ),
                ),
                (
                    "child_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="wjs_review.message",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="wjs_review.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageRecipients",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="True only if the message has been read by this recipient.",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="When True, the name of this recipient will not be shown.",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wjs_review.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_messages",
                through="wjs_review.MessageRecipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipients",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="related_messages",
            field=models.ManyToManyField(
                related_name="children_messages",
                through="wjs_review.MessageThread",
                to="wjs_review.message",
                verbose_name="Related messages",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="to_be_forwarded_to",
            field=models.ForeignKey(
                blank=True,
                help_text="The final recipient that this message was intended for",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pre_moderation_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="final recipient",
            ),
        ),
        migrations.CreateModel(
            name="LatexPreamble",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preamble", models.TextField()),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "LaTeX preamble",
            },
        ),
        migrations.CreateModel(
            name="EditorRevisionRequest",
            fields=[
                (
                    "revisionrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.revisionrequest",
                    ),
                ),
                (
                    "article_history",
                    models.JSONField(blank=True, null=True, verbose_name="Article history"),
                ),
                (
                    "confirm_previous_version",
                    models.BooleanField(default=False, verbose_name="Confirm version"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=999, null=True, verbose_name="Title"),
                ),
                (
                    "abstract",
                    core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name="Abstract"),
                ),
                (
                    "cover_letter_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.file",
                        verbose_name="Cover letter file",
                    ),
                ),
                (
                    "data_figure_files",
                    models.ManyToManyField(blank=True, related_name="+", to="core.file"),
                ),
                (
                    "editor_decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revision_request",
                        to="wjs_review.editordecision",
                        verbose_name="Editor decision",
                    ),
                ),
                (
                    "manuscript_files",
                    models.ManyToManyField(blank=True, related_name="+", to="core.file"),
                ),
                (
                    "review_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="review.reviewround",
                        verbose_name="Review round",
                    ),
                ),
                (
                    "source_files",
                    models.ManyToManyField(blank=True, related_name="+", to="core.file"),
                ),
                (
                    "supplementary_files",
                    models.ManyToManyField(blank=True, related_name="+", to="core.supplementaryfile"),
                ),
            ],
            options={
                "ordering": ("date_requested",),
            },
            bases=("review.revisionrequest",),
        ),
        migrations.CreateModel(
            name="PermissionAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("all", "visible (identity revealed)"),
                            ("no_names", "visible (identity NOT revealed)"),
                            ("deny", "not visibile"),
                        ],
                        default="no_names",
                        max_length=255,
                        verbose_name="Permission set",
                    ),
                ),
                (
                    "permission_secondary",
                    models.CharField(
                        choices=[("all", "visible"), ("deny", "not visibile")],
                        default="deny",
                        help_text="Used to assign permissions to parts of the objects (eg: cover letter etc)",
                        max_length=255,
                        verbose_name="Extra permission set",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission assignment",
                "verbose_name_plural": "Permission assignments",
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="wjs_review__content_b08449_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="editordecision",
            unique_together={("workflow", "review_round", "decision")},
        ),
    ]
