# Generated by Django 3.2.19 on 2023-07-28 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleworkflow",
            options={"verbose_name": "Article workflow", "verbose_name_plural": "Article workflows"},
        ),
    ]
