# Generated by Django 4.2.20 on 2025-04-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleworkflow",
            name="arxiv_category",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Arxiv category"),
        ),
    ]
