# Generated by Django 4.2.20 on 2025-05-14 10:40

import plugins.wjs_review.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0002_articleworkflow_arxiv_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=plugins.wjs_review.models.WjsBleachCharField(
                blank=True, default="", help_text="The content of the message.", verbose_name="body"
            ),
        ),
    ]
