# Generated by Django 3.2.19 on 2023-10-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0004_introduce_message_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editordecision",
            name="decision",
            field=models.CharField(
                choices=[
                    ("accept", "Accept"),
                    ("reject", "Reject"),
                    ("minorRevision", "Minor revision"),
                    ("majorRevision", "Major revision"),
                    ("not_suitable", "Not suitable"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="EditorRevisionRequest",
            fields=[
                (
                    "revisionrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.revisionrequest",
                    ),
                ),
                (
                    "review_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="review.reviewround",
                        verbose_name="Review round",
                    ),
                ),
            ],
            bases=("review.revisionrequest",),
        ),
    ]
