# Generated by Django 4.2.16 on 2025-05-21 09:45

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drop unused indexes.

    See specs#1541
    """

    dependencies = [  # noqa: RUF012
        ("wjs_review", "0003_alter_message_body"),
    ]

    # Note: ATM we have indexes for all languages; we only manage papers in the languages marked below,
    # but here we drop all indexes for cleanliness.
    # "abstract_cy_ft_idx" gin (abstract_cy)
    # "abstract_de_ft_idx" gin (abstract_de)
    # "abstract_en_ft_idx" gin (abstract_en)  <<== *
    # "abstract_es_ft_idx" gin (abstract_es)  <<==
    # "abstract_fr_ft_idx" gin (abstract_fr)
    # "abstract_nl_ft_idx" gin (abstract_nl)
    # "abstract_pt_ft_idx" gin (abstract_pt)  <<==

    operations = [  # noqa: RUF012
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS abstract_cy_ft_idx;
            DROP INDEX IF EXISTS abstract_de_ft_idx;
            DROP INDEX IF EXISTS abstract_en_ft_idx;
            DROP INDEX IF EXISTS abstract_es_ft_idx;
            DROP INDEX IF EXISTS abstract_fr_ft_idx;
            DROP INDEX IF EXISTS abstract_nl_ft_idx;
            DROP INDEX IF EXISTS abstract_pt_ft_idx;
            """,
            reverse_sql="""
            CREATE INDEX abstract_cy_ft_idx ON submission_article (abstract_cy);
            CREATE INDEX abstract_de_ft_idx ON submission_article (abstract_de);
            CREATE INDEX abstract_en_ft_idx ON submission_article (abstract_en);
            CREATE INDEX abstract_es_ft_idx ON submission_article (abstract_es);
            CREATE INDEX abstract_fr_ft_idx ON submission_article (abstract_fr);
            CREATE INDEX abstract_nl_ft_idx ON submission_article (abstract_nl);
            CREATE INDEX abstract_pt_ft_idx ON submission_article (abstract_pt);
            """,
            # Note that a different kind of index might be better:
            # CREATE INDEX abstract_en_ft_idx ON submission_article USING GIN (to_tsvector('english', abstract_en));
        ),
    ]
