# Generated by Django 3.2.19 on 2023-09-25 16:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0003_rename_workflow_states"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A short description of the message or the subject of the email.",
                        max_length=111,
                        verbose_name="to",
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, default="", help_text="The content of the message.", max_length=1111),
                ),
                (
                    "message_type",
                    models.TextField(
                        choices=[
                            ("Standard", "Standard message (notifications are sent)"),
                            ("Silent", "Silent message (no notification is sent)"),
                        ],
                        default="Standard",
                        help_text="The type of the message: std messages trigger notifications, silent ones do not.",
                        verbose_name="type",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The author of the message (for system message, use wjs-support account)",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="authored_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="from",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageRecipients",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "read",
                    models.BooleanField(
                        default=False, help_text="True only if the message has been read by this recipient."
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False, help_text="When True, the name of this recipient will not be shown."
                    ),
                ),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wjs_review.message")),
                (
                    "recipient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_messages", through="wjs_review.MessageRecipients", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
