# Generated by Django 4.2.23 on 2025-07-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0004_drop_index_on_abstract"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleworkflow",
            name="arxiv_category",
        ),
    ]
