# Generated by Django 3.2.19 on 2023-10-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0004_create_editorrevisionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=models.ManyToManyField(blank=True, null=True, to="core.File"),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.TextField(
                choices=[
                    ("Standard", "Standard message (notifications are sent)"),
                    ("Silent", "Silent message (no notification is sent)"),
                    ("Verbose", "Write all the body in the notification email."),
                    ("Verbose ma non troppo", "Add the first 10 lines of the body to the message"),
                ],
                default="Standard",
                help_text="The type of the message: std messages trigger notifications, silent ones do not.",
                verbose_name="type",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["content_type", "object_id"], name="wjs_review__content_b08449_idx"),
        ),
    ]
