# Generated by Django 4.2.24 on 2025-10-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0005_remove_articleworkflow_arxiv_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowreviewassignment",
            name="tex_report_pdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tex_report_files",
                to="core.file",
                verbose_name="Tex report PDF file",
            ),
        ),
    ]
