# Generated by Django 3.2.19 on 2023-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0005_auto_20231006_0606"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorrevisionrequest",
            name="cover_letter_file",
            field=models.FileField(blank=True, null=True, upload_to="", verbose_name="Cover letter file"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="WorkflowReviewAssignment",
            fields=[
                (
                    "reviewassignment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.reviewassignment",
                    ),
                ),
                ("author_note_visible", models.BooleanField(default=True, verbose_name="Author note visible")),
            ],
            bases=("review.reviewassignment",),
        ),
    ]
