# Generated by Django 4.2.24 on 2025-10-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0006_workflowreviewassignment_tex_report_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="latexpreamble",
            name="report_preamble",
            field=models.TextField(
                default=r"""
    \documentclass[a4paper,12pt]{article}
    \usepackage[utf8]{inputenc}
    \usepackage[TS1,T1]{fontenc}
    \usepackage{amsmath}
    \usepackage{amssymb}
    \usepackage{textcomp}
    \usepackage{xcolor}
    \usepackage{mathrsfs}
    \usepackage{dynkin-diagrams}
    \definecolor{posurl}{cmyk}{.9 .9 0 0}
    \usepackage[
        colorlinks=true,
        urlcolor=posurl,
        anchorcolor=posurl,
        citecolor=posurl,
        filecolor=posurl,
        linkcolor=posurl,
        menucolor=posurl,
        linktocpage=true,
        pdfa=true
    ]{hyperref}
    \usepackage{tikz}
    \usepackage{mlcodes}
    \usepackage{dsfont}

    \newcommand{\watermark}[2][550,-190]{%
      \fontfamily{ucr}\fontseries{m}\fontsize{28.3}{28.3}\selectfont%
      \color{gray}%
      \put(#1){\rotatebox{-90}{#2}}%
    }

    \AddToHook{shipout/background}{\watermark{REPORT {1}}}

    \begin{document}
    \parindent=0pt
    {\Large\scshape Report on {1}} \\
    Date: \today
    \bigskip
    \bigskip

    \hrule depth 1pt
    \bigskip
    \bigskip

    Author(s): {2}
    \bigskip

    Title: {3}
    \bigskip
    \bigskip

    Received: {4}
    \bigskip
    \bigskip

    \hrule depth 1pt
    \bigskip
    \bigskip

    \parindent=1em
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%        write your report in LaTeX       %%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%  starting in the next empty line below  %%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%   (no need of \begin{document} etc.)  %%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    """,
                help_text=(
                    "LaTeX preamble prepended to reviewers and editors reports. "
                    "Please note that it should end with \\begin{document}."
                ),
            ),
            preserve_default=False,
        ),
    ]
