# Generated by Django 3.2.19 on 2023-12-11 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0006_editorrevisionrequest_cover_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleworkflow",
            name="eo_in_charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="EO in charge",
            ),
        ),
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="review_round",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="review.reviewround",
                verbose_name="Review round",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.TextField(
                choices=[
                    ("Standard", "Standard message (notifications are sent)"),
                    ("Silent", "Silent message (no notification is sent)"),
                    ("Verbose", "Write all the body in the notification email."),
                    ("Verbose ma non troppo", "Add the first 10 lines of the body to the message"),
                    ("System log message", "A system message"),
                ],
                default="Standard",
                help_text="The type of the message: std messages trigger notifications, silent ones do not.",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A short description of the message or the subject of the email.",
                max_length=111,
                verbose_name="subject",
            ),
        ),
    ]
