# Generated by Django 4.2.24 on 2025-10-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0007_latexpreamble_report_preamble"),
    ]

    operations = [
        migrations.AddField(
            model_name="editordecision",
            name="decision_editor_report_pdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editor_report_pdf_files",
                to="core.file",
                verbose_name="Editor report in PDF",
            ),
        ),
    ]
