# Generated by Django 4.2.24 on 2025-10-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0008_editordecision_decision_editor_report_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="wjseditorassignment",
            name="editor_report_pdf_draft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editor_report_pdf_files_draft",
                to="core.file",
                verbose_name="Editor report in PDF draft version",
            ),
        ),
    ]
