# Generated by Django 4.2.25 on 2025-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0009_wjseditorassignment_editor_report_pdf_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorrevisionrequest",
            name="authors_contributions",
            field=models.TextField(blank=True, null=True, verbose_name="Authors contributions"),
        ),
    ]
