# Generated by Django 3.2.19 on 2024-01-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0009_alter_message_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read_by_eo",
            field=models.BooleanField(
                default=False,
                help_text="True when a member of the EO marks as read a message exchanged by other two actors",
            ),
        ),
    ]
