# Generated by Django 3.2.19 on 2024-02-01 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wjs_review", "0010_add_read_by_eo_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("REEA1", "Reviewer should evaluate assignment"),
                            ("REEA2", "Reviewer should evaluate assignment"),
                            ("REEA3", "Reviewer should evaluate assignment"),
                            ("REWR1", "Reviewer should write review"),
                            ("REWR2", "Reviewer should write review"),
                            ("EDSR1", "Editor should select reviewer"),
                            ("EDSR2", "Editor should select reviewer"),
                            ("EDSR3", "Editor should select reviewer"),
                            ("EDMD1", "Editor should make decision"),
                            ("EDMD2", "Editor should make decision"),
                            ("EDMD3", "Editor should make decision"),
                        ],
                        max_length=5,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_due", models.DateField()),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                ("disabled", models.BooleanField(default=False)),
                ("clemency_days", models.IntegerField()),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "hide_actor_name",
                    models.BooleanField(
                        default=True,
                        help_text="Hide the name of the actor in the message body / subject / From-header",
                    ),
                ),
                ("message_subject", models.TextField()),
                ("message_body", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders_that_i_send",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders_that_i_receive",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Reminder", "verbose_name_plural": "Reminders"},
        ),
    ]
