# Generated by Django 4.2.25 on 2026-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0010_editorrevisionrequest_authors_contributions"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorrevisionrequest",
            name="revision_flow_type",
            field=models.CharField(
                choices=[("confirm", "Confirm"), ("metadata", "Metadata"), ("full", "Minor / Major")],
                default="full",
                max_length=10,
                verbose_name="Revision flow type",
            ),
            preserve_default=False,
        ),
    ]
