# Generated by Django 4.2.25 on 2026-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0011_editorrevisionrequest_revision_flow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowreviewassignment",
            name="shared_report",
            field=models.BooleanField(default=False, verbose_name="Shared report"),
        ),
    ]
