# Generated by Django 3.2.19 on 2024-02-13 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0012_add_prophy_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editordecision",
            name="decision",
            field=models.CharField(
                choices=[
                    ("accept", "Accept"),
                    ("reject", "Reject"),
                    ("minor_revisions", "Minor revision"),
                    ("major_revisions", "Major revision"),
                    ("tech_revisions", "Technical revision"),
                    ("not_suitable", "Not suitable"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="review_round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="review.reviewround", verbose_name="Review round"
            ),
        ),
    ]
