# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0012_workflowreviewassignment_shared_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleworkflow",
            name="last_major_revision",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last major revision"),
        ),
        migrations.AddField(
            model_name="editorrevisionrequest",
            name="last_major_revision",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last major revision"),
        ),
    ]
