# Generated by Django 3.2.19 on 2024-04-04 13:12

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0014_auto_20240329_0012"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleworkflow",
            name="supplementary_files_at_acceptance",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="_wjs_review_articleworkflow_supplementary_files_at_acceptance_+",
                to="core.SupplementaryFile",
            ),
        ),
    ]
