# Generated by Django 4.2.30 on 2026-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0013_add_last_major_revision_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.TextField(
                choices=[
                    ("System log message", "A system message"),
                    ("User hijacked action log message", "A hijacking notification message"),
                    ("User note", "Notes to self"),
                    ("User message", "User direct message"),
                ],
                db_index=True,
                default="System log message",
                help_text="Define the message source / scope",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="object_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
