# Generated by Django 3.2.19 on 2024-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0014_supp_files_at_acceptance"),
    ]

    operations = [
        migrations.AddField(
            model_name="prophyaccount",
            name="first_name",
            field=models.CharField(max_length=300, null=True, verbose_name="First name"),
        ),
        migrations.AddField(
            model_name="prophyaccount",
            name="last_name",
            field=models.CharField(max_length=300, null=True, verbose_name="Last name"),
        ),
        migrations.AddField(
            model_name="prophyaccount",
            name="middle_name",
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Middle name"),
        ),
        migrations.AddField(
            model_name="prophyaccount",
            name="suffix",
            field=models.CharField(blank=True, help_text="Name suffix eg. jr", max_length=300, null=True),
        ),
    ]
