# Generated by Django 4.2.30 on 2026-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0014_alter_message_message_type_alter_message_object_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["created"], name="wjs_review__created_d90fad_idx"),
        ),
    ]
