# Generated by Django 3.2.19 on 2024-04-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0015_modify_prophy_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="code",
            field=models.CharField(
                choices=[
                    ("REEA1", "Reviewer should evaluate assignment"),
                    ("REEA2", "Reviewer should evaluate assignment"),
                    ("REEA3", "Reviewer should evaluate assignment"),
                    ("REWR1", "Reviewer should write review"),
                    ("REWR2", "Reviewer should write review"),
                    ("EDSR1", "Editor should select reviewer"),
                    ("EDSR2", "Editor should select reviewer"),
                    ("EDSR3", "Editor should select reviewer"),
                    ("EDMD1", "Editor should make decision"),
                    ("EDMD2", "Editor should make decision"),
                    ("EDMD3", "Editor should make decision"),
                    ("AUMJR1", "Author should submit major revision"),
                    ("AUMJR2", "Author should submit major revision"),
                    ("AUMIR1", "Author should submit minor revision"),
                    ("AUMIR2", "Author should submit minor revision"),
                    ("AUTCR1", "Author should submit technical revision"),
                    ("AUTCR2", "Author should submit technical revision"),
                    ("DIRASED1", "Director should assign editor"),
                    ("DIRASED2", "Director should assign editor"),
                ],
                max_length=10,
            ),
        ),
    ]
