# Generated by Django 4.2.25 on 2026-05-05 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0089_keyword_created_keyword_deactivated_keyword_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0015_message_wjs_review__created_d90fad_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="revision_flow_type",
            field=models.CharField(
                choices=[
                    ("confirm", "Confirmation of previous version"),
                    ("metadata", "Metadata change"),
                    ("full", "Revision submission"),
                ],
                max_length=10,
                verbose_name="Revision flow type",
            ),
        ),
        migrations.CreateModel(
            name="AttentionCondition",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        help_text="Stable functional code identifying the condition type.", max_length=64
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")], default="automatic", max_length=16
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable description shown to the user.",
                        max_length=512,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("expired", "Expired"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=99,
                        help_text="Display priority: lower number = higher priority. Derived from the original check order in article_requires_{role}_attention methods.",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(default=django.utils.timezone.now, help_text="When this AC becomes visible."),
                ),
                (
                    "valid_until",
                    models.DateTimeField(blank=True, help_text="When this AC expires (null = never).", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attention_conditions",
                        to="submission.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attention_conditions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attention condition",
                "verbose_name_plural": "Attention conditions",
                "ordering": ["priority", "created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="ac_user_status_idx"),
                    models.Index(fields=["article", "status"], name="ac_article_status_idx"),
                ],
                "unique_together": {("article", "user", "code")},
            },
        ),
    ]
