# Generated by Django 3.2.19 on 2024-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0016_add_message_relations_and_forward"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleworkflow",
            name="production_flag_galleys_ok",
            field=models.BooleanField(default=False, verbose_name="The latest galley generation was successful"),
        ),
        migrations.AddField(
            model_name="articleworkflow",
            name="production_flag_no_checks_needed",
            field=models.BooleanField(
                default=True, verbose_name="No special check is required on the latest typesetted files"
            ),
        ),
        migrations.AddField(
            model_name="articleworkflow",
            name="production_flag_no_queries",
            field=models.BooleanField(
                default=False, verbose_name="The latest typesetted files contain no queries for the author"
            ),
        ),
    ]
