# Generated by Django 3.2.19 on 2024-04-02 01:36

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0017_add_production_flags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="editorrevisionrequest",
            options={"ordering": ("date_requested",)},
        ),
        migrations.AlterField(
            model_name="articleworkflow",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("EditorToBeSelected", "Editor to be selected"),
                    ("EditorSelected", "Editor selected"),
                    ("Submitted", "Submitted"),
                    ("ToBeRevised", "To be revised"),
                    ("Withdrawn", "Withdrawn"),
                    ("Rejected", "Rejected"),
                    ("IncompleteSubmission", "Incomplete submission"),
                    ("NotSuitable", "Not suitable"),
                    ("PaperHasEditorReport", "Paper has editor report"),
                    ("Accepted", "Accepted"),
                    ("TypesetterSelected", "Typesetter selected"),
                    ("PaperMightHaveIssues", "Paper might have issues"),
                    ("Proofreading", "Proofreading"),
                    ("ReadyForTypesetter", "Ready for typesetter"),
                    ("Published", "Published"),
                    ("ReadyForPublication", "Ready for publication"),
                    ("SendToEditorForCheck", "Send to editor for check"),
                ],
                default="IncompleteSubmission",
                max_length=50,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="editordecision",
            name="decision",
            field=models.CharField(
                choices=[
                    ("accept", "Accept"),
                    ("reject", "Reject"),
                    ("minor_revisions", "Minor revision"),
                    ("major_revisions", "Major revision"),
                    ("tech_revisions", "Technical revision"),
                    ("not_suitable", "Not suitable"),
                    ("requires_resubmission", "Requires resubmission"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="PastEditorAssignment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_assigned", models.DateTimeField(verbose_name="Date assigned")),
                ("date_unassigned", models.DateTimeField(verbose_name="Date unassigned")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="submission.article", verbose_name="Article"
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Editor"
                    ),
                ),
                (
                    "review_rounds",
                    models.ManyToManyField(blank=True, to="review.ReviewRound", verbose_name="Managed review rounds"),
                ),
            ],
            options={
                "verbose_name": "Past editor assignment",
                "verbose_name_plural": "Past editor assignments",
            },
        ),
        migrations.CreateModel(
            name="PermissionAssignment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "permission",
                    models.CharField(
                        choices=[("all", "All"), ("no_names", "Hide names")],
                        default="no_names",
                        max_length=255,
                        verbose_name="Permission set",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission assignment",
                "verbose_name_plural": "Permission assignments",
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
    ]
