# Generated by Django 3.2.19 on 2024-05-15 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0017_add_pasteditorassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasteditorassignment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="past_editor_assignments",
                to="submission.article",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="permissionassignment",
            name="permission",
            field=models.CharField(
                choices=[("all", "All"), ("no_names", "Hide names"), ("deny", "Deny permission")],
                default="no_names",
                max_length=255,
                verbose_name="Permission set",
            ),
        ),
        migrations.CreateModel(
            name="WjsEditorAssignment",
            fields=[
                (
                    "editorassignment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="review.editorassignment",
                    ),
                ),
                (
                    "review_rounds",
                    models.ManyToManyField(blank=True, to="review.ReviewRound", verbose_name="Managed review rounds"),
                ),
            ],
            options={
                "verbose_name": "Past editor assignment",
                "verbose_name_plural": "Past editor assignments",
                "get_latest_by": "assigned",
            },
            bases=("review.editorassignment",),
        ),
    ]
