# Generated by Django 5.2.17 on 2026-09-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0018_resolve_stale_appeal_acs"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasteditorassignment",
            name="on_appeal",
            field=models.BooleanField(
                default=False,
                help_text="The editor was removed when the Editorial Office opened an appeal.",
                verbose_name="Removed on appeal",
            ),
        ),
    ]
