# Generated by Django 3.2.20 on 2024-05-19 16:26

from django.db import migrations


def create_wjs_assignment(apps, schema_editor):
    WjsEditorAssignment = apps.get_model("wjs_review", "WjsEditorAssignment")
    EditorAssignment = apps.get_model("review", "EditorAssignment")

    for assignment in EditorAssignment.objects.all():
        assignment_id = assignment.pk
        assignment.__class__ = WjsEditorAssignment
        assignment.editorassignment_ptr_id = assignment_id
        assignment.save()


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0018_add_wjs_permission_assignment"),
    ]

    operations = [migrations.RunPython(create_wjs_assignment, reverse_code=migrations.RunPython.noop)]
