# Generated by Django 3.2.19 on 2024-05-28 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0019_migrate_editor_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleworkflow",
            name="latest_state_change",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
