# Generated by Django 3.2.20 on 2024-05-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0020_latest_state_change"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wjseditorassignment",
            options={
                "get_latest_by": "assigned",
                "verbose_name": "Editor assignment",
                "verbose_name_plural": "Editor assignments",
            },
        ),
        migrations.AlterField(
            model_name="editordecision",
            name="decision",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("accept", "Accept"),
                    ("reject", "Reject"),
                    ("minor_revisions", "Minor revision"),
                    ("major_revisions", "Major revision"),
                    ("tech_revisions", "Technical revision"),
                    ("not_suitable", "Not suitable"),
                    ("requires_resubmission", "Requires resubmission"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="permissionassignment",
            name="permission_secondary",
            field=models.CharField(
                choices=[("all", "Allow"), ("deny", "Deny")],
                default="deny",
                help_text="Used to assign permissions to parts of the objects (eg: cover letter etc)",
                max_length=255,
                verbose_name="Extra permission set",
            ),
        ),
        migrations.AlterField(
            model_name="permissionassignment",
            name="permission",
            field=models.CharField(
                choices=[("all", "Allow"), ("no_names", "Hide names"), ("deny", "Deny")],
                default="no_names",
                max_length=255,
                verbose_name="Permission set",
            ),
        ),
    ]
