# Generated by Django 3.2.19 on 2024-06-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0021_add_permission_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleworkflow",
            name="production_flag_galleys_ok",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Not tested"), (2, "Test failed"), (3, "Test succeeded")],
                default=1,
                verbose_name="The status of the latest galleys",
            ),
        ),
    ]
