# Generated by Django 3.2.19 on 2024-06-25 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0059_alter_prepublicationchecklistitem_completed_by"),
        ("submission", "0071_merge_0070_auto_20230120_1546_0070_auto_20230208_1233"),
        ("wjs_review", "0022_articleworkflow_production_flag_galleys_ok"),
    ]

    operations = [
        migrations.CreateModel(
            name="WjsSection",
            fields=[
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="submission.section",
                    ),
                ),
                ("doi_sectioncode", models.CharField(blank=True, max_length=2, null=True)),
                ("pubid_and_tex_sectioncode", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("submission.section",),
        ),
        migrations.CreateModel(
            name="LatexPreamble",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preamble", models.TextField()),
                ("journal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="journal.journal")),
            ],
            options={
                "verbose_name": "LaTeX preamble",
            },
        ),
    ]
