# Generated by Django 3.2.19 on 2024-07-03 09:12

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0024_articleworkflow_latex_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleworkflow",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("EditorToBeSelected", "Editor to be selected"),
                    ("EditorSelected", "Editor selected"),
                    ("Submitted", "Submitted"),
                    ("ToBeRevised", "To be revised"),
                    ("Withdrawn", "Withdrawn"),
                    ("Rejected", "Rejected"),
                    ("IncompleteSubmission", "Incomplete submission"),
                    ("NotSuitable", "Not suitable"),
                    ("PaperHasEditorReport", "Paper has editor report"),
                    ("Accepted", "Accepted"),
                    ("TypesetterSelected", "Typesetter selected"),
                    ("PaperMightHaveIssues", "Paper might have issues"),
                    ("Proofreading", "Proofreading"),
                    ("ReadyForTypesetter", "Ready for typesetter"),
                    ("Published", "Published"),
                    ("ReadyForPublication", "Ready for publication"),
                    ("SendToEditorForCheck", "Send to editor for check"),
                    ("PublicationInProgress", "Publication in progress"),
                ],
                default="IncompleteSubmission",
                max_length=50,
                verbose_name="State",
            ),
        ),
    ]
