# Generated by Django 3.2.19 on 2024-07-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0025_add_state_publicationinprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleworkflow",
            name="social_media_short_description",
            field=models.TextField(blank=True, null=True, verbose_name="Short description for social media"),
        ),
    ]
