# Generated by Django 4.2.11 on 2024-06-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0026_add_social_media_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleworkflow",
            name="supplementary_files_at_acceptance",
            field=models.ManyToManyField(blank=True, null=True, related_name="+", to="core.supplementaryfile"),
        ),
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="data_figure_files",
            field=models.ManyToManyField(blank=True, null=True, related_name="+", to="core.file"),
        ),
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="manuscript_files",
            field=models.ManyToManyField(blank=True, null=True, related_name="+", to="core.file"),
        ),
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="source_files",
            field=models.ManyToManyField(blank=True, related_name="+", to="core.file"),
        ),
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="supplementary_files",
            field=models.ManyToManyField(blank=True, null=True, related_name="+", to="core.supplementaryfile"),
        ),
    ]
