# Generated by Django 3.2.19 on 2024-07-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0027_alter_articleworkflow_supplementary_files_at_acceptance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowreviewassignment",
            name="author_note_visible",
            field=models.BooleanField(default=True, verbose_name="Author's cover letter visible (if available)"),
        ),
    ]
