# Generated by Django 3.2.19 on 2024-07-12 12:29

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0028_author_note_naming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleworkflow",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("EditorToBeSelected", "Editor to be selected"),
                    ("EditorSelected", "Editor selected"),
                    ("Submitted", "Submitted"),
                    ("ToBeRevised", "To be revised"),
                    ("Withdrawn", "Withdrawn"),
                    ("Rejected", "Rejected"),
                    ("IncompleteSubmission", "Incomplete submission"),
                    ("NotSuitable", "Not suitable"),
                    ("PaperHasEditorReport", "Paper has editor report"),
                    ("Accepted", "Accepted"),
                    ("TypesetterSelected", "Typesetter selected"),
                    ("PaperMightHaveIssues", "Paper might have issues"),
                    ("Proofreading", "Proofreading"),
                    ("ReadyForTypesetter", "Ready for typesetter"),
                    ("Published", "Published"),
                    ("ReadyForPublication", "Ready for publication"),
                    ("SendToEditorForCheck", "Send to editor for check"),
                    ("UnderAppeal", "Under appeal"),
                ],
                default="IncompleteSubmission",
                max_length=50,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="editordecision",
            name="decision",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("accept", "Accept"),
                    ("reject", "Reject"),
                    ("minor_revisions", "Minor revision"),
                    ("major_revisions", "Major revision"),
                    ("tech_revisions", "Technical revision"),
                    ("not_suitable", "Not suitable"),
                    ("requires_resubmission", "Requires resubmission"),
                    ("open_appeal", "Open appeal"),
                ],
                max_length=255,
            ),
        ),
    ]
