# Generated by Django 3.2.20 on 2024-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_review", "0028_author_note_naming"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="verbosity",
            field=models.TextField(
                choices=[
                    ("Full", "Full message content is sent by email"),
                    ("Timeline", "Timeline only, no email sent"),
                    ("Email", "Email only, not recorded in timeline"),
                    ("Reduced", "Reduced message sent my email"),
                ],
                default="Full",
                help_text="Define the message verbosity: ie: the amount of content sent my email / set in the timeline",
                verbose_name="Verbosity",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.TextField(
                choices=[
                    ("System log message", "A system message"),
                    ("User hijacked action log message", "A hijacking notification message"),
                    ("User note", "Notes to self"),
                    ("User message", "User direct message"),
                ],
                default="System log message",
                help_text="Define the message source / scope",
                verbose_name="Type",
            ),
        ),
    ]
