# Generated by Django 4.2.11 on 2024-08-27 07:33

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0030_add_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowreviewassignment",
            name="report_form_answers",
            field=models.JSONField(default=dict, verbose_name="Report form answers"),
        ),
    ]
