# Generated by Django 4.2.11 on 2024-08-30 12:32

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0031_report_form_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editordecision",
            name="decision_internal_note",
        ),
    ]
