# Generated by Django 4.2.11 on 2024-09-06 10:50

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0032_remove_editordecision_decision_internal_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowreviewassignment",
            name="editor_invite_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editor_invite_messages",
                to="wjs_review.message",
                verbose_name="Editor invite message",
            ),
        ),
    ]
