# Generated by Django 4.2.11 on 2024-09-11 09:05

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0033_editor_invite_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleworkflow",
            name="production_flag_galleys_ok",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Galleys not tested"),
                    (2, "Galleys generation failed"),
                    (3, "Galleys generation succeeded"),
                ],
                default=1,
                verbose_name="The status of the latest galleys",
            ),
        ),
        migrations.AlterField(
            model_name="articleworkflow",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("EditorToBeSelected", "Editor to be selected"),
                    ("EditorSelected", "Editor selected"),
                    ("Submitted", "Submitted"),
                    ("ToBeRevised", "To be revised"),
                    ("Withdrawn", "Withdrawn"),
                    ("Rejected", "Rejected"),
                    ("IncompleteSubmission", "Incomplete submission"),
                    ("NotSuitable", "Not suitable"),
                    ("PaperHasEditorReport", "Paper has editor report"),
                    ("Accepted", "Accepted"),
                    ("TypesetterSelected", "Typesetter selected"),
                    ("PaperMightHaveIssues", "Paper might have issues"),
                    ("Proofreading", "Proofreading"),
                    ("ReadyForTypesetter", "Ready for typesetter"),
                    ("Published", "Published"),
                    ("ReadyForPublication", "Ready for publication"),
                    ("SendToEditorForCheck", "Send to editor for check"),
                    ("PublicationInProgress", "Publication in progress"),
                    ("UnderAppeal", "Under appeal"),
                ],
                default="IncompleteSubmission",
                max_length=50,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="editordecision",
            name="decision",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("accept", "Accept"),
                    ("reject", "Reject"),
                    ("minor_revisions", "Minor revision"),
                    ("major_revisions", "Major revision"),
                    ("tech_revisions", "Change Metadata"),
                    ("not_suitable", "Not suitable"),
                    ("requires_resubmission", "Requires resubmission"),
                    ("open_appeal", "Open appeal"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="attachments",
            field=models.ManyToManyField(blank=True, null=True, to="core.file", verbose_name="Attachments"),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, default="", max_length=1111, verbose_name="body"),
        ),
        migrations.AlterField(
            model_name="message",
            name="read_by_eo",
            field=models.BooleanField(
                default=False,
                help_text="True when a member of the EO marks as read a message exchanged by other two actors",
                verbose_name="Read by EO",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_messages",
                through="wjs_review.MessageRecipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipients",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="related_messages",
            field=models.ManyToManyField(
                related_name="children_messages",
                through="wjs_review.MessageThread",
                to="wjs_review.message",
                verbose_name="Related messages",
            ),
        ),
        migrations.AlterField(
            model_name="permissionassignment",
            name="permission",
            field=models.CharField(
                choices=[
                    ("all", "visible (editor's and reviewer's identity revealed)"),
                    ("no_names", "visible (editor’s identity NOT revealed)"),
                    ("deny", "not visibile"),
                ],
                default="no_names",
                max_length=255,
                verbose_name="Permission set",
            ),
        ),
        migrations.AlterField(
            model_name="permissionassignment",
            name="permission_secondary",
            field=models.CharField(
                choices=[("all", "visible"), ("deny", "not visibile")],
                default="deny",
                help_text="Used to assign permissions to parts of the objects (eg: cover letter etc)",
                max_length=255,
                verbose_name="Extra permission set",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders_that_i_send",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actor",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="clemency_days",
            field=models.IntegerField(default=0, verbose_name="Clemency dats"),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="code",
            field=models.CharField(
                choices=[
                    ("REEA1", "Reviewer should evaluate assignment"),
                    ("REEA2", "Reviewer should evaluate assignment"),
                    ("REEA3", "Reviewer should evaluate assignment"),
                    ("REWR1", "Reviewer should write review"),
                    ("REWR2", "Reviewer should write review"),
                    ("EDSR1", "Editor should select reviewer"),
                    ("EDSR2", "Editor should select reviewer"),
                    ("EDSR3", "Editor should select reviewer"),
                    ("EDMD1", "Editor should make decision"),
                    ("EDMD2", "Editor should make decision"),
                    ("EDMD3", "Editor should make decision"),
                    ("AUMJR1", "Author should submit major revision"),
                    ("AUMJR2", "Author should submit major revision"),
                    ("AUMIR1", "Author should submit minor revision"),
                    ("AUMIR2", "Author should submit minor revision"),
                    ("AUTCR1", "Author should submit technical revision"),
                    ("AUTCR2", "Author should submit technical revision"),
                    ("DIRASED1", "Director should assign editor"),
                    ("DIRASED2", "Director should assign editor"),
                ],
                max_length=10,
                verbose_name="Reminder code",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="date_due",
            field=models.DateField(
                help_text="The date when the reminder should be sent",
                verbose_name="Date due",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="date_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="The date when the reminder was sent",
                null=True,
                verbose_name="Date sent",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Disabled"),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="hide_actor_name",
            field=models.BooleanField(
                default=True,
                help_text="Hide the name of the actor in the message body / subject / From-header",
                verbose_name="Hide actor name",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="message_body",
            field=models.TextField(verbose_name="Message body"),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="message_subject",
            field=models.TextField(verbose_name="Message subject"),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders_that_i_receive",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipient",
            ),
        ),
    ]
