# Generated by Django 4.2.11 on 2024-09-11 14:39

import plugins.wjs_review.models
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0034_alter_articleworkflow_production_flag_galleys_ok_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=plugins.wjs_review.models.WjsBleachCharField(
                blank=True, default="", help_text="The content of the message."
            ),
        ),
    ]
