# Generated by Django 4.2.11 on 2024-09-10 09:32

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0035_janewaybleachfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasteditorassignment",
            name="decline_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Decline reason"),
        ),
        migrations.AddField(
            model_name="pasteditorassignment",
            name="decline_text",
            field=models.TextField(blank=True, null=True, verbose_name="Decline optional text"),
        ),
    ]
