# Generated by Django 4.2.11 on 2024-09-12 13:56

import plugins.wjs_review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0036_pasteditorassignment_decline_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowreviewassignment",
            name="send_review_file",
            field=models.BooleanField(default=False, verbose_name="Send review file to Author"),
        ),
    ]
