# Generated by Django 4.2.15 on 2024-10-15 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_merge_20240621_0722"),
        ("wjs_review", "0038_editorrevisionrequest_abstract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleworkflow",
            name="publication_galleys_source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.file",
                verbose_name="Source file of the published galleys, prepared by the system from the last TA source files",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="verbosity",
            field=models.TextField(
                choices=[
                    ("Full", "Full message content is sent by email"),
                    ("Timeline", "Timeline only, no email sent"),
                    ("Email", "Email only, not recorded in timeline"),
                ],
                default="Full",
                help_text="Define the message verbosity: ie: the amount of content sent my email / set in the timeline",
                verbose_name="Verbosity",
            ),
        ),
    ]
