# Generated by Django 4.2.11 on 2024-10-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0039_articleworkflow_publication_galleys_source_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleworkflow",
            name="production_flag_no_checks_needed",
            field=models.BooleanField(
                default=False, verbose_name="No special check is required on the latest typesetted files"
            ),
        ),
    ]
