# Generated by Django 4.2.11 on 2024-11-02 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_review", "0040_publishable_flag_default_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="editordecision",
            name="editor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="editor_decisions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Editor",
            ),
            preserve_default=False,
        ),
    ]
