# Generated by Django 4.2.11 on 2024-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0041_editordecision_editor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasteditorassignment",
            name="decline_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select a decline reason"),
                    ("JCOM_BUSY", "Already too busy with JCOM editorial work"),
                    ("BUSY", "Too busy in general"),
                    ("OUTSIDE_EXPERTISE", "Paper outside my area of expertise"),
                    ("NO_REVIEWER", "Unable to find an appropriate reviewer"),
                    ("OTHER", "Other"),
                ],
                null=True,
                verbose_name="Decline reason",
            ),
        ),
    ]
