# Generated by Django 4.2.11 on 2024-11-03 15:33

from django.db import migrations, models
from plugins.wjs_review.plugin_settings import JUMP_URL, PLUGIN_NAME


def fix_jump_url(apps, schema_editor):
    WorkflowElement = apps.get_model("core", "WorkflowElement")
    WorkflowElement.objects.filter(element_name=PLUGIN_NAME).update(jump_url=JUMP_URL)


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0042_alter_pasteditorassignment_decline_reason"),
    ]

    operations = [migrations.RunPython(fix_jump_url, migrations.RunPython.noop)]
