# Generated by Django 4.2.11 on 2024-11-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0043_fix_jump_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="data_figure_files",
            field=models.ManyToManyField(blank=True, related_name="+", to="core.file"),
        ),
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="manuscript_files",
            field=models.ManyToManyField(blank=True, related_name="+", to="core.file"),
        ),
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="supplementary_files",
            field=models.ManyToManyField(blank=True, related_name="+", to="core.supplementaryfile"),
        ),
    ]
