# Generated by Django 4.2.11 on 2024-11-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0044_alter_editorrevisionrequest_data_figure_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorrevisionrequest",
            name="editor_decision",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revision_request",
                to="wjs_review.editordecision",
                verbose_name="Editor decision",
            ),
        ),
    ]
