# Generated by Django 4.2.11 on 2024-11-09 15:36

from django.db import migrations


def set_decision_on_revision(apps, schema_editor):
    """
    Set the editor decision on the revision request if it's not set already.

    This data migration is only useful to ensure a smooth transition from the current state in dev / local databases.
    It will have no effect in production as there will be no pre-existing data.

    We can even delete this after we have migrated all the environments.
    """
    EditorRevisionRequest = apps.get_model("wjs_review", "EditorRevisionRequest")
    EditorDecision = apps.get_model("wjs_review", "EditorDecision")
    for decision in EditorDecision.objects.all():
        revision_request = EditorRevisionRequest.objects.filter(
            article=decision.workflow.article, review_round=decision.review_round
        ).first()
        if revision_request and not revision_request.editor_decision:
            revision_request.editor_decision = decision
            revision_request.save()
    # As of 2024-11-07 only one "orphaned" revision request was found, it's safe to delete as we have lot of dirty data
    EditorRevisionRequest.objects.filter(editor_decision__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0044_editorrevisionrequest_editor_decision"),
    ]

    operations = [migrations.RunPython(set_decision_on_revision, migrations.RunPython.noop)]
