# Generated by Django 4.2.11 on 2024-11-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0045_set_decision_on_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="editor_decision",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revision_request",
                to="wjs_review.editordecision",
                verbose_name="Editor decision",
            ),
        ),
    ]
