# Generated by Django 4.2.11 on 2024-11-21 21:14

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0046_alter_editorrevisionrequest_editor_decision"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wjssection",
            options={"verbose_name": "WJS Section"},
        ),
        migrations.AddField(
            model_name="wjssection",
            name="description",
            field=core.model_utils.JanewayBleachField(blank=True, default=""),
        ),
    ]
