# Generated by Django 4.2.16 on 2024-12-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_merge_20240621_0722"),
        ("wjs_review", "0047_alter_wjssection_options_wjssection_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="cover_letter_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.file",
                verbose_name="Cover letter file",
            ),
        ),
    ]
