# Generated by Django 4.2.11 on 2025-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0048_alter_editorrevisionrequest_cover_letter_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorrevisionrequest",
            name="title",
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name="Title"),
        ),
    ]
