# Generated by Django 4.2.11 on 2025-02-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wjs_review", "0049_alter_editorrevisionrequest_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowreviewassignment",
            name="author_note_visible",
        ),
        migrations.RemoveField(
            model_name="workflowreviewassignment",
            name="send_review_file",
        ),
    ]
