# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-06 14:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0073_auto_20220630_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCod', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('jhep', 'jhep'), ('pos', 'pos'), ('jcap', 'jcap'), ('jstat', 'jstat'), ('jinst', 'jinst'), ('jcom', 'jcom'), ('jcomal', 'jcomal'), ('sgp', 'sgp')], max_length=6)),
                ('notes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JCOMProfile',
            fields=[
                ('janeway_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profession', models.IntegerField(choices=[(0, 'A researcher in S&T studies, science communication or neighbouring field'), (1, 'A practitioner in S&T (e.g. journalist, museum staff, writer, ...)'), (2, 'An active scientist'), (3, 'Other')], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.account',),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='correspondence',
            unique_together=set([('account', 'userCod', 'source')]),
        ),
    ]
