# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-24 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0071_xslt_1-4-2'),
    ]

    operations = [
        migrations.CreateModel(
            name='JCOMProfile',
            fields=[
                ('janeway_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profession', models.IntegerField(choices=[(0, 'A researcher in S&T studies, science communication or neighbouring field'), (1, 'A practitioner in S&T (e.g. journalist, museum staff, writer, ...)'), (2, 'An active scientist'), (3, 'Other')], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.account',),
        ),
    ]
