# Generated by Django 1.11.29 on 2022-09-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jcomprofile",
            name="gdpr_checkbox",
            field=models.BooleanField(default=False, verbose_name="GDPR acceptance checkbox"),
        ),
    ]
