# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-28 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jcom_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jcomprofile',
            name='account_ptr',
        ),
        migrations.AddField(
            model_name='jcomprofile',
            name='janeway_account',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
