# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-27 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jcom_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCod', models.CharField(max_length=100)),
                ('source', models.IntegerField(choices=[(0, 'jhep'), (1, 'pos'), (2, 'jcap'), (3, 'jinst'), (4, 'jstat'), (5, 'jcom'), (6, 'jcomal'), (7, 'sgp')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usercod',
            unique_together=set([('account', 'userCod', 'source')]),
        ),
    ]
