# Generated by Django 1.11.29 on 2022-09-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0002_jcomprofile_gdpr_checkbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="jcomprofile",
            name="invitation_token",
            field=models.CharField(default="", max_length=500, verbose_name="Invitation token"),
        ),
    ]
