# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-28 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jcom_profile', '0002_auto_20220627_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercod',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercods', to=settings.AUTH_USER_MODEL),
        ),
    ]
