# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-04 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcom_profile', '0003_auto_20220628_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercod',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
