"""New Janeway setting to parametrize title of additional files upload form."""
# Generated by Django 1.11.29 on 2022-10-05 14:20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jcom_profile", "0003_jcomprofile_invitation_token"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop),
    ]
