# Generated by Django 1.11.29 on 2022-11-16 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_merge_20221004_1031"),
        ("journal", "0055_issue_isbn"),
        ("jcom_profile", "0005_auto_20221018_0924"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialissue",
            name="is_open_for_submission",
        ),
        migrations.AddField(
            model_name="specialissue",
            name="close_date",
            field=models.DateTimeField(
                blank=True, help_text="Authors cannot submit to this special issue after this date", null=True
            ),
        ),
        migrations.AddField(
            model_name="specialissue",
            name="description",
            field=models.TextField(default="desc", help_text="Description or abstract"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialissue",
            name="documents",
            field=models.ManyToManyField(to="core.File"),
        ),
        migrations.AddField(
            model_name="specialissue",
            name="journal",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="journal.Journal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialissue",
            name="open_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Authors can submit to this special issue only after this date",
            ),
        ),
        migrations.AddField(
            model_name="specialissue",
            name="short_name",
            field=models.SlugField(
                default="CODE", help_text="Short name or code (please only [a-zA-Z0-9_-]", max_length=21
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="specialissue",
            name="name",
            field=models.CharField(help_text="Name / title / long name", max_length=121),
        ),
    ]
