# Generated by Django 1.11.29 on 2022-11-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0007_auto_20221118_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorassignmentparameters",
            name="keywords",
            field=models.ManyToManyField(blank=True, through="jcom_profile.EditorKeyword", to="submission.Keyword"),
        ),
    ]
