# Generated by Django 1.11.29 on 2022-12-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0069_delete_blank_keywords"),
        ("jcom_profile", "0008_auto_20221130_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialissue",
            name="allowed_sections",
            field=models.ManyToManyField(to="submission.Section"),
        ),
    ]
