# Generated by Django 1.11.29 on 2022-12-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jcom_profile", "0009_specialissue_allowed_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlewrapper",
            name="nid",
            field=models.IntegerField(
                blank=True,
                help_text="Drupal's Node ID. Keeping for future reference and extra check during import.",
                null=True,
                unique=True,
            ),
        ),
    ]
