# Generated by Django 1.11.29 on 2022-12-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0010_articlewrapper_nid"),
        ("jcom_profile", "0012_auto_20221216_2208"),
    ]

    operations = []
