# Generated by Django 1.11.29 on 2023-04-05 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from wjs.jcom_profile.models import _get_language_choices


class Migration(migrations.Migration):
    dependencies = [
        ("jcom_profile", "0019_auto_20230413_1415"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="language",
            field=models.CharField(
                blank=True,
                choices=_get_language_choices(),
                max_length=10,
                verbose_name="Preferred newsletter's language",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Anonymous user email"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Newsletter recipient user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipient",
            unique_together={("user", "journal"), ("email", "journal")},
        ),
        migrations.AddField(
            model_name="newsletter",
            name="journal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletter",
                to="journal.Journal",
                verbose_name="Journal",
            ),
        ),
    ]
