"""Update "publication_alert" settings and set them `is_translatable=True`."""

# Generated by Django 1.11.29 on 2023-04-13 12:15

from core.models import Setting
from django.db import migrations


def make_publication_alert_settings_translatable(apps, schema_editor):
    """Update "publication_alert" settings and set them `is_translatable=True`."""
    for setting in Setting.objects.filter(name__startswith="publication_alert"):
        setting.is_translatable = True
        setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0018_add_blank_true_to_recipient_user"),
    ]

    operations = [
        migrations.RunPython(make_publication_alert_settings_translatable),
    ]
