# Generated by Django 1.11.29 on 2023-04-12 12:46

from django.db import migrations


# https://docs.djangoproject.com/en/1.11/topics/migrations/#data-migrations
def fill_newsletter_journal_field_with_first_journal(apps, schema_editor):
    Journal = apps.get_model("journal", "Journal")
    Newsletter = apps.get_model("jcom_profile", "Newsletter")

    first_journal = Journal.objects.first()
    if first_journal:
        for newsletter in Newsletter.objects.all():
            newsletter.journal = first_journal
            newsletter.save()


# Newsletter.journal was created as a NULLable field to allow the migration to run without chicken-and-egg errors
# about empty database that does not have Journal(s) (as of now during tests, but not only there).
# This data migration gets the first Journal in the database (at this stage there will be at least one) and
# saves it as Newsletter.journal.
class Migration(migrations.Migration):
    dependencies = [
        ("jcom_profile", "0019_recipient_language"),
    ]

    operations = [
        migrations.RunPython(fill_newsletter_journal_field_with_first_journal, migrations.RunPython.noop),
    ]
