# Generated by Django 1.11.29 on 2023-06-30 15:56
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jcom_profile", "0022_make_newsletter_journal_field_not_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="last_sent",
            field=models.DateTimeField(verbose_name="Last time newsletter emails have been sent to users"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Newsletter topics user",
            ),
        ),
    ]
