# Generated by Django 3.2.18 and mg on 2023-07-04 15:20

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_alter_account_preferred_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jcom_profile", "0023_auto_20230630_1756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondence",
            name="notes",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="used",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="jcomprofile",
            name="janeway_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="specialissue",
            name="documents",
            field=models.ManyToManyField(blank=True, limit_choices_to={"article_id": None}, null=True, to="core.File"),
        ),
    ]
