# Generated by Django 3.2.19 on 2023-07-13 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jcom_profile", "0024_merged_23_recipient_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="correspondence",
            unique_together={("account", "user_cod", "source", "email")},
        ),
    ]
