# Generated by Django 3.2.19 on 2023-12-05 23:10

from django.db import migrations

from wjs.jcom_profile.apps import GROUP_EO


def create_eo_group(apps, schema_editor):
    """Create the EO group."""
    Group = apps.get_model("auth", "Group")
    try:
        # we can't use get_or_create because it's a migration
        Group.objects.get(name=GROUP_EO)
    except Group.DoesNotExist:
        Group.objects.create(name=GROUP_EO)


class Migration(migrations.Migration):
    dependencies = [
        ("jcom_profile", "0026_recipient_confirmation_email_last_sent"),
    ]

    operations = [migrations.RunPython(create_eo_group, migrations.RunPython.noop)]
