# Generated by Django 3.2.19 on 2024-04-24 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jcom_profile", "0027_add_eo_group"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="editorassignmentparameters",
            unique_together={("editor", "journal")},
        ),
    ]
