# Generated by Django 4.2.11 on 2024-08-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0028_add_unique_together_editor_journal_in_editorassignmentparameters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialissue",
            name="allowed_sections",
        ),
        migrations.RemoveField(
            model_name="specialissue",
            name="documents",
        ),
        migrations.RemoveField(
            model_name="specialissue",
            name="editors",
        ),
        migrations.RemoveField(
            model_name="specialissue",
            name="invitees",
        ),
        migrations.RemoveField(
            model_name="specialissue",
            name="journal",
        ),
        migrations.DeleteModel(
            name="ArticleWrapper",
        ),
        migrations.DeleteModel(
            name="SpecialIssue",
        ),
    ]
