# Generated by Django 4.2.11 on 2024-09-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0031_jcomprofile_keywords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueparameters",
            name="latex_fragment",
            field=models.CharField(
                blank=True,
                help_text="LaTeX fragment that should appear in the PDF of all papers of this issue.",
                max_length=500,
                null=True,
                verbose_name="LaTeX fragment",
            ),
        ),
    ]
