# Generated by Django 4.2.11 on 2024-11-13 23:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jcom_profile", "0032_issueparameters_latex_fragment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EditorAssignmentParameters",
            new_name="StaffWorkloadParameters",
        ),
    ]
