# Generated by Django 4.2.11 on 2024-11-14 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "jcom_profile",
            "0033_rename_editorassignmentparameters_staffworkloadparameters",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="editorkeyword",
            old_name="editor_parameters",
            new_name="parameters",
        ),
        migrations.RenameField(
            model_name="staffworkloadparameters",
            old_name="editor",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="staffworkloadparameters",
            unique_together={("user", "journal")},
        ),
    ]
