# Generated by Django 4.2.11 on 2024-11-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "jcom_profile",
            "0034_rename_editor_parameters_editorkeyword_parameters_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EditorKeyword",
            new_name="StaffKeyword",
        ),
    ]
