# Generated by Django 4.2.11 on 2024-12-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0035_rename_editorkeyword_staffkeyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="jcomprofile",
            name="usernotes",
            field=models.TextField(blank=True, default="", null=True, verbose_name="User notes"),
        ),
    ]
