# Generated by Django 4.2.22 on 2026-03-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0036_add_usernotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="jcomprofile",
            name="gdpr_acceptance",
            field=models.DateTimeField(blank=True, null=True, verbose_name="GDPR acceptance date"),
        ),
        migrations.AddField(
            model_name="jcomprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("D", "Rather not say")],
                default="",
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="jcomprofile",
            name="records_arxiv",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="My Records on ArXiv"),
        ),
        migrations.AddField(
            model_name="jcomprofile",
            name="records_inspire",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="My Records on Inspire"),
        ),
        migrations.AddField(
            model_name="jcomprofile",
            name="records_other",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Others (personal website, records on Google Scholar/ResearchGate, etc)",
            ),
        ),
        migrations.AddField(
            model_name="jcomprofile",
            name="records_scix",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="My Records on SciX"),
        ),
        migrations.AddField(
            model_name="jcomprofile",
            name="year_of_birth",
            field=models.IntegerField(blank=True, null=True, verbose_name="Year of birth"),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="source",
            field=models.CharField(
                choices=[
                    ("jhep", "jhep"),
                    ("pos", "pos"),
                    ("jcap", "jcap"),
                    ("jstat", "jstat"),
                    ("jinst", "jinst"),
                    ("jcom", "jcom"),
                    ("jcomal", "jcomal"),
                    ("sgp", "sgp"),
                    ("tex", "TeX"),
                ],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="issueparameters",
            name="batch_publish",
            field=models.BooleanField(default=False, verbose_name="Batch published"),
        ),
        migrations.AlterField(
            model_name="jcomprofile",
            name="profession",
            field=models.IntegerField(
                choices=[
                    (0, "A researcher in S&T studies, science communication or neighbouring field"),
                    (1, "A practitioner in S&T (e.g. journalist, museum staff, writer, ...)"),
                    (2, "An active scientist"),
                    (3, "Other profession"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jcomprofile",
            name="usernotes",
            field=models.TextField(blank=True, default="", verbose_name="User notes"),
        ),
    ]
