# Generated by Django 4.2.22 on 2026-03-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0037_jcomprofile_gdpr_acceptance_jcomprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jcomprofile",
            name="alternative_email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Institutional email address"),
        ),
    ]
