# Generated by Django 4.2.22 on 2026-04-30 10:54

from django.db import migrations
from django.utils.timezone import now


def set_gdpr_acceptance_date(apps, schema_editor):
    JCOMProfile = apps.get_model("jcom_profile", "JCOMProfile")
    JCOMProfile.objects.filter(gdpr_acceptance__isnull=True, gdpr_checkbox=True).update(gdpr_acceptance=now())


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0038_jcomprofile_alternative_email"),
    ]

    operations = [migrations.RunPython(set_gdpr_acceptance_date, migrations.RunPython.noop)]
