# Generated by Django 4.2.30 on 2026-06-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0039_set_gdpr_acceptance"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffworkloadparameters",
            name="enabled",
            field=models.BooleanField(
                default=True,
                verbose_name="I am generally available to be assigned new submissions",
            ),
        ),
        migrations.AddField(
            model_name="staffworkloadparameters",
            name="vacancy_end",
            field=models.DateField(blank=True, null=True, verbose_name="Vacancy end"),
        ),
        migrations.AddField(
            model_name="staffworkloadparameters",
            name="vacancy_start",
            field=models.DateField(blank=True, null=True, verbose_name="Vacancy start"),
        ),
    ]
