#
# Manutenzione globale JCOM
#
<VirtualHost *:80>
    ServerName      jcom.sissa.it
    Define LOG_NAME jcom

    ServerAdmin webmaster@sissamedialab.it
    DocumentRoot /var/www/default

    LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" %{ms}Tms http" combinedx
    CustomLog ${APACHE_LOG_DIR}/${LOG_NAME}-access.log combinedx
    ErrorLog  ${APACHE_LOG_DIR}/${LOG_NAME}-error.log

    Redirect permanent "/" "https://jcom.sissa.it/"

</VirtualHost>

<VirtualHost *:443>
    ServerName      jcom.sissa.it
    Define LOG_NAME jcom

    ServerAdmin webmaster@sissamedialab.it
    DocumentRoot /var/www/maint-pages

    LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" %{ms}Tms https" combinedx
    CustomLog ${APACHE_LOG_DIR}/${LOG_NAME}-access.log combinedx
    ErrorLog  ${APACHE_LOG_DIR}/${LOG_NAME}-error.log

    ProxyPreserveHost On
    RewriteEngine On

    # Domain email autoconfig (_prima_ di ProxyPass):
    Include sites-available/email-autoconfig.inc


    RewriteEngine On
    RewriteCond %{SCRIPT_FILENAME} !jcom.maintenance.html
    RewriteRule ^(.*)$ /$1 [R=503,L]
    ErrorDocument 503 /jcom.maintenance.html

    Header Set Pragma "no-cache"
    Header Set Expires "Thu, 1 Jan 1970 00:00:00 GMT"
    Header Set Cache-Control "max-age=0, no-store, no-cache, must-revalidate"
    Header Unset ETag
    FileETag None

    Include                 options-ssl-apache.inc
    SSLCertificateFile      /etc/ssl/private/garr/stheno_sissa_it_fullchain.crt
    SSLCertificateKeyFile   /etc/ssl/private/garr/stheno_sissa_it.key

</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr et
