# Enable Gunicorn in wjs-prod.
# See to-gunicorn.yml for wjs-test instances.
# Run as `ansible-playbook -i wjs-prod, to-gunicorn-prod.yml --check
---
- name: Replace daphne with gunicorn
  hosts: wjs-prod
  remote_user: root
  become: yes
  vars:
    wjs_user_id: "1000"


  tasks:
    - name: Enable mod_rewrite
      apache2_module:
        name: rewrite
        state: present
      notify: restart apache

    - name: Copy Apache/application-server socket configuration
      copy:
        src: apache/apache-proxy-and-socket.inc
        dest: /etc/apache2/conf-available/wjs/apache-proxy-and-socket.inc
        owner: root
        group: root
        mode: '0644'

    - name: Render and copy Apache virtualhost configuration
      copy:
        src: apache/wjs-prod.conf
        dest: /etc/apache2/sites-available/wjs.conf
        owner: root
        group: root
        mode: '0644'




    - name: Copy wjs systemd tmpfiles configuration
      copy:
        src: systemd/wjs-rundir.conf
        dest: /etc/tmpfiles.d/wjs-rundir.conf
        owner: root
        group: root
        mode: '0644'

    - name: Create files specified in wjs-rundir.conf
      command: systemd-tmpfiles --create /etc/tmpfiles.d/wjs-rundir.conf

    - name: Ensure systemd user config directory exists for wjs user
      file:
        path: /home/wjs/.config/systemd/user
        state: directory
        owner: wjs
        group: wjs
        mode: '0755'

    - name: Copy gunicorn systemd service to user config
      template:
        src: systemd/gunicorn.service
        dest: /home/wjs/.config/systemd/user/gunicorn.service
        owner: wjs
        group: wjs
        mode: '0644'
      notify: reload user systemd

    - name: Copy logrotate configuration for wjs
      template:
        src: etc/logrotate-wjs.conf
        dest: /etc/logrotate.d/wjs
        owner: root
        group: root
        mode: '0644'



    - name: Install python packages in virtualenv
      # Note that this should not be necessary, because the new packages are
      # explicit dependencies of our package, but doing it here allows us to
      # not have any imposition on the order in which we do the switch-over
      # (e.g. first install the code, then to the swithc-over or viceversa).
      pip:
        name:
          - uvicorn
          - uvicorn-worker
          - gunicorn
        virtualenv: /home/wjs/.virtualenvs/janeway
      become_user: wjs



    - name: Disable the old Apache janeway-xxx.conf site (points to uwsgi)
      command: a2dissite janeway.conf
      ignore_errors: yes
      # notify: reload apache  # NB: do not reload apache just yet!

    - name: Enable Apache wjs.conf site (points to gunicorn)
      command: a2ensite wjs.conf

    - name: Add SECURE_PROXY_SSL_HEADER setting if missing
      lineinfile:
        path: /home/wjs/janeway/src/core/settings/__init__.py
        line: "SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')"
        state: present
      become_user: wjs


    # Obsolete
    - name: Stop uwsgi, if running, by renaming the config file
      command: mv /home/wjs/uwsgi/janeway.ini /home/wjs/uwsgi/DISABLED__janeway.ini
      args:
        creates: /home/wjs/uwsgi/DISABLED__janeway.ini
      become_user: wjs
      ignore_errors: yes


    - name: Stop daphne service if running
      ansible.builtin.systemd_service:
        name: daphne.service
        state: stopped
        enabled: false
        scope: user
      become_user: wjs
      ignore_errors: yes
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ wjs_user_id }}"

    - name: Start gunicorn service as user wjs
      ansible.builtin.systemd_service:
        name: gunicorn.service
        state: restarted
        enabled: true
        scope: user
      become_user: wjs
      # should not be necessary, because wjs is `loginctl enable-linger`, but...
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ wjs_user_id }}"
      tags: pesky



    - name: Reload Apache configuration
      service:
        name: apache2
        state: reloaded


    - name: Fix service name in deploy script
      replace:
        path: /home/wjs/deploy.sh
        regexp: 'daphne'
        replace: 'gunicorn'
      become_user: wjs


  handlers:
    - name: reload user systemd
      ansible.builtin.systemd_service:
        daemon_reload: yes
        scope: user
      become_user: wjs
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ wjs_user_id }}"
